# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - physics-revision

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  JAVA_VERSION: '11'
  AZURE_WEBAPP_NAME: 'physics-revision'
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_WEBAPP_PUBLISH_PROFILE: secrets.AZUREAPPSERVICE_PUBLISHPROFILE_90D6E72968134D7EB42C7843300158AC

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@master

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build with Maven
        run: mvn clean install -P production --file pom.xml

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.jar'
