# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - physics-revision-app-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://fitzpatrick.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6c6662d5a8fa4cc4a02aa5396c111ad8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8b02cdf3d2fe438892becb966efed8c4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: fitzpatrick.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6c6662d5a8fa4cc4a02aa5396c111ad8 }}/physicsrevision:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'physics-revision-app-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a77474c6a8434f9ab427e851b2ec5532 }}
        images: 'fitzpatrick.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6c6662d5a8fa4cc4a02aa5396c111ad8 }}/physicsrevision:${{ github.sha }}'